version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/php"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/python"
    schedule:
      interval: "weekly"
